version: '3.8'
# noinspection ComposeUnknownKeys
name: ifchat

services:
  postgres:
    container_name: ifchat_postgres
    image: postgres:16.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ifchat

volumes:
  postgres-data: